### ISSUE TITLE
Stream Schema; https://www.jsonfeed.org

### ISSUE THREAD

**Issue by trovster** [jakealbaugh/social#1]
The example for the "stream" seems a lot like a JSON implementation of RSS. It seems there is an initiative which is recommending a schema for that; https://www.jsonfeed.org

To keep things standardised it might be worth mentioning that schema in the documentation / updating your example to match.

What do you think?

**Comment by ja-k-e** [comment]
i really appreciate this and the benefits of a standardized approach. at the moment, i feel like the informal nature of the current iteration is fun and most approachable for folks who haven't written JSON before.

definitely going to keep this in mind, but imo it would be a bit overkill to start requiring this of anyone at this stage. currently prioritizing curiosity and possibility over formality.

thanks for bringing this specific initiative to my attention, was aware of some convos in this arena, but not this project in particular!
